name: flutter_mapas_osm
description: "Trabalhando com mapas"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  provider: ^6.1.5+1
  battery_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/OIP.webp"

flutter:
  uses-material-design: true
  assets:
    - assets/
